"""Create database

Revision ID: 0a6885dfcdcd
Revises: 
Create Date: 2022-01-21 21:20:17.442598

"""
from alembic import op
from app.models import GUID
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0a6885dfcdcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'logs',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('Message', sa.Text(), nullable=False),
        sa.Column('Level', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=False),
        sa.Column('Source', sa.Text(), nullable=False),
        sa.Column('Platform', sa.Text(), nullable=True),
        sa.Column('created_on', sa.DateTime(), nullable=True),
        sa.Column('Log File', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'scheduled_tasks',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('start', sa.DateTime(), nullable=False),
        sa.Column('interval', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cancelled', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_name'), 'scheduled_tasks', ['name'], unique=False)
    op.create_table(
        'tasks',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('complete', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_scheduled_tasks_name'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_table('logs')
    # ### end Alembic commands ###
