"""Create existing financials tables

Revision ID: 66f431f6e401
Revises: 0a6885dfcdcd
Create Date: 2022-01-23 17:50:11.559765

"""
from alembic import op
from app.models import GUID
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '66f431f6e401'
down_revision = '0a6885dfcdcd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'receipts',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('merchant_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('value', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'sales',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('id_sale', sa.Integer(), nullable=True),
        sa.Column('merchant_id', sa.Integer(), nullable=True),
        sa.Column('chip_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('status', sa.Text(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table(
        'transactions',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('transaction_id', sa.Integer(), nullable=True),
        sa.Column('merchant_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.Text(), nullable=True),
        sa.Column('value', sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('sales')
    op.drop_table('receipts')
    # ### end Alembic commands ###
