"""Create conversations table

Revision ID: 837a5dae6d0d
Revises: 8d35e704f043
Create Date: 2022-01-24 10:27:00.862912

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '837a5dae6d0d'
down_revision = '8d35e704f043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conversations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('conversation_id', sa.String(length=50), nullable=False),
        sa.Column('creation_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('conversation_id'),
    )
    op.create_table(
        'messages',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('conversation_id', sa.String(length=50), nullable=True),
        sa.Column('body', sa.Text(), nullable=True),
        sa.Column('sender', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ('conversation_id',), ['conversations.conversation_id'], onupdate='CASCADE', ondelete='CASCADE',
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('conversations')
    # ### end Alembic commands ###
