"""Create actions table

Revision ID: 8d35e704f043
Revises: 66f431f6e401
Create Date: 2022-01-23 22:57:03.364070

"""
from alembic import op
from app.models import GUID
from sqlalchemy.sql import func
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '8d35e704f043'
down_revision = '66f431f6e401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'actions',
        sa.Column('id', GUID(length=50), nullable=False),
        sa.Column('name', sa.Text(), nullable=False),
        sa.Column('completed', sa.Boolean(), nullable=True, server_default='0'),
        sa.Column('timestamp', sa.DateTime(), nullable=True, server_default=func.now()),
        sa.Column('conversation_id', sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actions')
    # ### end Alembic commands ###
